---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: "Kubernetes Cluster 1"
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://my-proxy:8000
#   HTTPS_PROXY=http://my-proxy:8000
#   NO_PROXY=127.0.0.1,localhost,master-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 192.168.40.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 4 # Number of virtual cpus
    cap: 20 # Set the Maximum Amount of Physical CPU Time Used by a Virtual CPU
    memory: 4096 # In MB
  workers:
    count: 1
    cpu: 6
    cap: 20
    memory: 4096
# Mount additional shared folders from the host into each virtual machine.
# Note that the project directory is automatically mounted at /vagrant.
# shared_folders:
#   - host_path: ../images
#     vm_path: /vagrant/images
software:
  box: bento/ubuntu-22.04
  cilium: 1.14.2
  containerd: 1.7.2-0ubuntu1~22.04.1
  # To skip the dashboard installation, set its version to an empty value or comment it out:
  #dashboard: 2.7.0
  kubernetes: 1.28.2-00
  os: xUbuntu_22.04
